# Generated by Django 5.0 on 2024-01-18 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=150)),
                ('ing_category', models.CharField(choices=[('<4', 'menos de 4 ingredientes'), ('<8', 'menos de 8 ingredientes'), ('>8', 'mas de 8 ingredientes')], max_length=100)),
                ('description', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('reference', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=16)),
                ('measure_quantity', models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('g', 'Gramo (g)'), ('mg', 'Miligramo (mg)'), ('l', 'Litro (l)'), ('dl', 'Decilitro (dl)'), ('ml', 'Mililitro (ml)')], default=('kg', 'Kilogramo (kg)'), max_length=255)),
                ('recipe_fgk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
